---
title: "Advent of Code 2023 Day 5"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 5: If You Give A Seed A Fertilizer \-\--

You take the boat and find the gardener right where you were told he would be: managing a giant "garden" that looks more to you like a farm.

"A water source? Island Island *is* the water source!" You point out that Snow Island isn't receiving any water.

"Oh, we had to stop the water because we *ran out of sand* to [filter](https://en.wikipedia.org/wiki/Sand_filter) it with! Can't make snow with dirty water. Don't worry, I'm sure we'll get more sand soon; we only turned off the water a few days\... weeks\... oh no." His face sinks into a look of horrified realization.

"I've been so busy making sure everyone here has food that I completely forgot to check why we stopped getting more sand! There's a ferry leaving soon that is headed over in that direction - it's much faster than your boat. Could you please go check it out?"

You barely have time to agree to this request when he brings up another. "While you wait for the ferry, maybe you can help us with our *food production problem*. The latest Island Island [Almanac](https://en.wikipedia.org/wiki/Almanac) just arrived and we're having trouble making sense of it."

The almanac (your puzzle input) lists all of the seeds that need to be planted. It also lists what type of soil to use with each kind of seed, what type of fertilizer to use with each kind of soil, what type of water to use with each kind of fertilizer, and so on. Every type of seed, soil, fertilizer and so on is identified with a number, but numbers are reused by each category - that is, soil `123` and fertilizer `123` aren't necessarily related to each other.

For example:

```         
seeds: 79 14 55 13  

seed-to-soil map: 
50 98 2 
52 50 48  

soil-to-fertilizer map: 
0 15 37 
37 52 2 
39 0 15  

fertilizer-to-water map: 
49 53 8 
0 11 42 
42 0 7 
57 7 4  

water-to-light map: 
88 18 7 
18 25 70  

light-to-temperature map: 
45 77 23 
81 45 19 
68 64 13  

temperature-to-humidity map: 
0 69 1 
1 0 69  

humidity-to-location map: 
60 56 37 
56 93 4 
```

The almanac starts by listing which seeds need to be planted: seeds `79`, `14`, `55`, and `13`.

The rest of the almanac contains a list of *maps* which describe how to convert numbers from a *source category* into numbers in a *destination category*. That is, the section that starts with `seed-to-soil map:` describes how to convert a *seed number* (the source) to a *soil number* (the destination). This lets the gardener and his team know which soil to use with which seeds, which water to use with which fertilizer, and so on.

Rather than list every source number and its corresponding destination number one by one, the maps describe entire *ranges* of numbers that can be converted. Each line within a map contains three numbers: the *destination range start*, the *source range start*, and the *range length*.

Consider again the example `seed-to-soil map`:

```         
50 98 2 
52 50 48 
```

The first line has a *destination range start* of `50`, a *source range start* of `98`, and a *range length* of `2`. This line means that the source range starts at `98` and contains two values: `98` and `99`. The destination range is the same length, but it starts at `50`, so its two values are `50` and `51`. With this information, you know that seed number `98` corresponds to soil number `50` and that seed number `99` corresponds to soil number `51`.

The second line means that the source range starts at `50` and contains `48` values: `50`, `51`, \..., `96`, `97`. This corresponds to a destination range starting at `52` and also containing `48` values: `52`, `53`, \..., `98`, `99`. So, seed number `53` corresponds to soil number `55`.

Any source numbers that *aren't mapped* correspond to the *same* destination number. So, seed number `10` corresponds to soil number `10`.

So, the entire list of seed numbers and their corresponding soil numbers looks like this:

```         
seed  soil 
0     0 
1     1 
...   ... 
48    48 
49    49 
50    52 
51    53 
...   ... 
96    98 
97    99 
98    50 
99    51 
```

With this map, you can look up the soil number required for each initial seed number:

-   Seed number `79` corresponds to soil number `81`.

-   Seed number `14` corresponds to soil number `14`.

-   Seed number `55` corresponds to soil number `57`.

-   Seed number `13` corresponds to soil number `13`.

The gardener and his team want to get started as soon as possible, so they'd like to know the closest location that needs a seed. Using these maps, find *the lowest location number that corresponds to any of the initial seeds*. To do this, you'll need to convert each seed number through other categories until you can find its corresponding *location number*. In this example, the corresponding types are:

-   Seed `79`, soil `81`, fertilizer `81`, water `81`, light `74`, temperature `78`, humidity `78`, *location `82`*.

-   Seed `14`, soil `14`, fertilizer `53`, water `49`, light `42`, temperature `42`, humidity `43`, *location `43`*.

-   Seed `55`, soil `57`, fertilizer `57`, water `53`, light `46`, temperature `82`, humidity `82`, *location `86`*.

-   Seed `13`, soil `13`, fertilizer `52`, water `41`, light `34`, temperature `34`, humidity `35`, *location `35`*.

So, the lowest location number in this example is *`35`*.

*What is the lowest location number that corresponds to any of the initial seed numbers?*

I don't really want to try to parse this input, but can create the variables manually without much effort.

```{python}
seeds = "3429320627 235304036 1147330745 114559245 1684000747 468955901 677937579 96599505 1436970021 26560102 3886049334 159534901 936845926 25265009 3247146679 95841652 3696363517 45808572 2319065313 125950148"

seeds = [int(x) for x in seeds.split()]

seed_to_soil = """583826644 2288418886 120919689
2666741396 3172314277 160907737
416244021 605500997 167582623
779666561 2280573809 7845077
704746333 908146497 74920228
845411123 2565941729 61831565
1527751557 3025978089 146336188
2827649133 2012274036 268299773
259640867 2409338575 156603154
0 2766337222 259640867
787511638 983066725 57899485
907242688 1526828044 485445992
1674087745 237273108 368227889
2180879562 1040966210 485861834
1392688680 773083620 135062877
3095948906 0 237273108
2042315634 2627773294 138563928""".split('\n')

seed_to_soil = [list(map(int, x.split())) for x in seed_to_soil]
seed_to_soil.sort()


soil_to_fertilizer = """3793729374 3825015981 63222599
1438266078 0 258943930
1292079166 1479426911 146186912
2816531945 2822520060 385496901
1078023340 1741334425 98335224
3856951973 3668871521 111838140
4180611137 3904426682 114356159
0 1958275780 804927654
3968790113 3380257222 80572704
843553208 2801828988 20691072
1724422279 286156201 594958638
3616894031 4018782841 39547646
1697210008 258943930 27212271
3700747997 3472761445 92981377
4101643138 3565742822 50848378
4152491516 3460829926 11931519
976862296 1378265867 101161044
2319380917 881114839 497151028
3380257222 4058330487 236636809
3656441677 3780709661 44306320
864244280 1845657764 112618016
1176358564 1625613823 115720602
4164423035 3888238580 16188102
3202028846 1839669649 5988115
804927654 2763203434 38625554
4049362817 3616591200 52280321""".split('\n')

soil_to_fertilizer = [list(map(int, x.split())) for x in soil_to_fertilizer]
soil_to_fertilizer.sort()

fertilizer_to_water = """3734704645 4081344261 116089008
474703780 198917265 194664963
1879970783 393582228 36617128
1197375949 1845422975 8989824
466658346 430199356 8045434
2310800010 2638298964 424967672
919557740 1398638397 135905600
3687134144 3790001806 1934146
3470663058 2339708475 216471086
1759740912 1126580170 64763562
896009775 1048686270 23547965
3348634097 3711378096 32073660
3091810489 2234799361 92321214
889058738 1119629133 6951037
2784472328 3743451756 46550050
2843610278 3063266636 231881310
1532834459 674183164 226906453
3273953517 2183514026 51285335
3075491588 4197433269 16318901
3325238852 3791935952 23395245
3689068290 3665741741 45636355
3384455721 3861402055 22006111
3406461832 3295147946 64201226
1412808810 438244790 32132927
3380707757 2556179561 3747964
3850793653 4001077593 80266668
1450046808 470377717 82787651
669368743 1626190154 219232821
1365871086 1072234235 46937724
3184131703 3969255894 11450375
1824504474 553165368 55466309
1206365773 1854412799 159505313
1055463340 906773661 141912609
3931060321 3359349172 306392569
2756139006 3883408166 28333322
193812194 608631677 65551487
2229584884 4213752170 81215126
3195582078 2559927525 78371439
259363681 1191343732 207294665
2183514026 3815331197 46070858
2735767682 3980706269 20371324
888601564 1119171959 457174
1916587911 901089617 5684044
1922271955 1534543997 91646157
4237452890 3911741488 57514406
2831022378 2327120575 12587900
1444941737 193812194 5105071""".split('\n')

fertilizer_to_water = [list(map(int, x.split())) for x in fertilizer_to_water]
fertilizer_to_water.sort()

water_to_light = """3241790649 0 474458786
1987249042 1535533387 1254541607
289948525 715361304 527138528
3716249435 1242499832 58349573
1051771035 3080023519 694575489
817087053 1300849405 234683982
1746346524 474458786 240902518
0 2790074994 289948525""".split('\n')

water_to_light = [list(map(int, x.split())) for x in water_to_light]
water_to_light.sort()

light_to_temperature = """2243197897 1858683458 54522139
694397455 637497541 323467072
3781060233 3489670799 513907063
2297720036 960964613 400594644
3448397921 3305645149 184025650
1096611912 137478840 356155107
2159128717 1774614278 84069180
1769470938 1913205597 389657779
1017864527 2302863376 78747385
3632423571 4003577862 148636662
281342434 1361559257 413055021
3393398302 4239967677 54999619
137478840 493633947 143863594
3305645149 4152214524 87753153
1452767019 2381610761 316703919""".split('\n')

light_to_temperature = [list(map(int, x.split())) for x in light_to_temperature]
light_to_temperature.sort()

temperature_to_humidity = """36297311 0 6725362
2219701249 4240213747 25288799
3578106372 1498215295 38253390
1356053404 1610598521 173674950
446166190 530183876 120299205
813026177 2579337380 225593633
133147960 367690092 61449909
223651565 500781338 29402538
253054103 174578005 193112087
194597869 6725362 29053696
566465395 85143164 1372917
799049686 3045085309 13976491
1529728354 3595799720 487441441
2420467399 2406340018 172679747
2593147146 1784273471 622066547
2244990048 3198005099 143889028
3437740738 4233433470 6780277
43022673 650483081 18483950
2407809136 1485557032 12658263
3215213693 1060498533 222527045
580905107 86516081 88061924
2017169795 1283025578 202531454
3710504883 2579019765 317615
61506623 429140001 71641337
3716287969 769584936 114202886
1328506806 3066097836 27546598
3703468847 3059061800 7036036
769584936 4265502546 29464750
1292525403 883787822 35981403
3710822498 919769225 5465471
3830490855 4083241161 150192309
3616359762 925234696 87109085
2388879076 3093644434 18930060
3529951620 1012343781 48154752
4220837460 1536468685 74129836
3444521015 3112574494 85430605
567838312 35779058 13066795
1038619810 3341894127 253905593
3980683164 2804931013 240154296
0 48845853 36297311""".split('\n')

temperature_to_humidity = [list(map(int, x.split())) for x in temperature_to_humidity]
temperature_to_humidity.sort()

humidity_to_location = """2609743610 4133079426 108193613
1608826026 1793129808 148682069
3749483646 1957417643 61460641
3216466252 4241273039 49689894
2717937223 1941811877 15605766
3810944287 1225630249 233181949
2124315534 3020458025 302014415
264620169 272336891 68907407
861861645 2458132363 209077985
4044126236 1458812198 250841060
3134115707 2375781818 82350545
1070939630 4290962933 4004363
2733542989 4089410242 43669184
1074943993 3479498485 533882033
2777212173 2018878284 356903534
2426329949 4013380518 76029724
333527576 0 7716722
3266156146 3346379827 130079823
2526267060 1709653258 83476550
1757508095 3476459650 3038835
0 7716722 264620169
1760546930 861861645 363768604
3396235969 2667210348 353247677
2502359673 3322472440 23907387""".split('\n')

humidity_to_location = [list(map(int, x.split())) for x in humidity_to_location]
humidity_to_location.sort()

```

```{python}
#| eval: false
# seeds= "79 14 55 13"
# 
# seeds = [int(x) for x in seeds.split()]
# 
# seed_to_soil = """50 98 2
# 52 50 48""".split('\n')
# 
# seed_to_soil = [list(map(int, x.split())) for x in seed_to_soil]
# 
# soil_to_fertilizer = """0 15 37
# 37 52 2
# 39 0 15""".split('\n')
# 
# soil_to_fertilizer = [list(map(int, x.split())) for x in soil_to_fertilizer]
# 
# fertilizer_to_water = """49 53 8
# 0 11 42
# 42 0 7
# 57 7 4""".split('\n')
# 
# fertilizer_to_water = [list(map(int, x.split())) for x in fertilizer_to_water]
# 
# water_to_light = """88 18 7
# 18 25 70""".split('\n')
# 
# water_to_light = [list(map(int, x.split())) for x in water_to_light]
# 
# light_to_temperature = """45 77 23
# 81 45 19
# 68 64 13""".split('\n')
# 
# light_to_temperature = [list(map(int, x.split())) for x in light_to_temperature]
# 
# temperature_to_humidity = """0 69 1
# 1 0 69""".split('\n')
# 
# temperature_to_humidity = [list(map(int, x.split())) for x in temperature_to_humidity]
# 
# humidity_to_location = """60 56 37
# 56 93 4""".split('\n')
# 
# humidity_to_location = [list(map(int, x.split())) for x in humidity_to_location]
```

Now we have to do something with this info.

```{python}

# seed_to_soil
# soil_to_fertilizer
# fertilizer_to_water
# water_to_light
# light_to_temperature
# temperature_to_humidity
# humidity_to_location

loc = []

def get_next(prev, lst):
    "Get the next thing in the process"
    for ss in lst: 
        if ss[1] <= prev <= ss[1] + ss[2]:
            return prev - ss[1] + ss[0]
    # if we don't return within the loop i.e. no mapping
    return prev
        
        
for s in seeds: 
    # print(s)
    ss = get_next(s, seed_to_soil)
    # print(ss)
    sf = get_next(ss, soil_to_fertilizer)
    # print(sf)
    fw = get_next(sf, fertilizer_to_water)
    # print(fw)
    wl = get_next(fw, water_to_light)
    # print(wl)
    lt = get_next(wl, light_to_temperature)
    # print(lt)
    th = get_next(lt, temperature_to_humidity)
    # print(th)
    hl = get_next(th, humidity_to_location)
    # print(hl)
    loc.append(hl)  
    # print()
    
min(loc)
```

## \-\-- Part Two \-\--

Everyone will starve if you only plant such a small number of seeds. Re-reading the almanac, it looks like the `seeds:` line actually describes *ranges of seed numbers*.

The values on the initial `seeds:` line come in pairs. Within each pair, the first value is the *start* of the range and the second value is the *length* of the range. So, in the first line of the example above:

```         
seeds: 79 14 55 13
```

This line describes two ranges of seed numbers to be planted in the garden. The first range starts with seed number `79` and contains `14` values: `79`, `80`, \..., `91`, `92`. The second range starts with seed number `55` and contains `13` values: `55`, `56`, \..., `66`, `67`.

Now, rather than considering four seed numbers, you need to consider a total of *27* seed numbers.

In the above example, the lowest location number can be obtained from seed number `82`, which corresponds to soil `84`, fertilizer `84`, water `84`, light `77`, temperature `45`, humidity `46`, and *location `46`*. So, the lowest location number is *`46`*.

Consider all of the initial seed numbers listed in the ranges on the first line of the almanac. *What is the lowest location number that corresponds to any of the initial seed numbers?*

```{python}

seeds = "3429320627 235304036 1147330745 114559245 1684000747 468955901 677937579 96599505 1436970021 26560102 3886049334 159534901 936845926 25265009 3247146679 95841652 3696363517 45808572 2319065313 125950148"

# seeds = "79 14 55 13"

seeds = [int(x) for x in seeds.split()]

mm = 285806460

for s,n in zip(seeds[:-1:2], seeds[1::2]): 
    print(str(s) + ': ' + str(n))
    for w in range(0, n, 1000):
        # print(s + w)
        ss = get_next(s + w, seed_to_soil)
        # print(ss)
        sf = get_next(ss, soil_to_fertilizer)
        # print(sf)
        fw = get_next(sf, fertilizer_to_water)
        # print(fw)
        wl = get_next(fw, water_to_light)
        # print(wl)
        lt = get_next(wl, light_to_temperature)
        # print(lt)
        th = get_next(lt, temperature_to_humidity)
        # print(th)
        hl = get_next(th, humidity_to_location)
        # print(hl)
        if hl < mm: 
            mm = hl
            print(str(s) + ': ' + str(n) + '; ' + str(mm))

        # print()

min(loc)

# 28580646
# 240320250
```

We only need to assess the ranges, since we know that anything in between is within the end points.

Problem: our ranges could expand, which means that if we start with passing one pair into the function, and we return two pairs of mappings, then we need to somehow loop through that list as we go through the different mappings. This means we should just pass the whole list through to the function in the first place, working with the different mapping lists as we go.

```{python}

seed_list = "3429320627 235304036 1147330745 114559245 1684000747 468955901 677937579 96599505 1436970021 26560102 3886049334 159534901 936845926 25265009 3247146679 95841652 3696363517 45808572 2319065313 125950148"

seed_list = [int(x) for x in seed_list.split()]

seeds = []

for s,n in zip(seed_list[:-1:2], seed_list[1::2]): 
    seeds.append([s,s+n])
    
seeds.sort()
    
# seeds


def get_range(prev, lst):
    "Get the next range in the process"
    "This receives the whole list of ranges, so we need to work through them"
    next = []
    for p in prev:
        for ss in lst: 
            # if the prev range is entirely within one mapping
            if ss[1] <= p[0] <= p[1] <= ss[1] + ss[2]:
                next.append([p[0] - ss[1] + ss[0], p[0] - ss[1] + ss[0]])
            # if we cross over boundaries of mappings, expand our list
            
            # this could also include not being within a mapping
        
        # if we don't return within the loop i.e. no mapping
        next.append(p)
    return next
  

ss = get_range(seeds, seed_to_soil)
# print(ss)
sf = get_range(ss, soil_to_fertilizer)
# print(sf)
fw = get_range(sf, fertilizer_to_water)
# print(fw)
wl = get_range(fw, water_to_light)
# print(wl)
lt = get_range(wl, light_to_temperature)
# print(lt)
th = get_range(lt, temperature_to_humidity)
# print(th)
hl = get_range(th, humidity_to_location)
# print(hl)

for h in hl:
    print(h[0])
    
```
