---
title: "Advent of Code 2023 Day 13"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 13: Point of Incidence \-\--

With your help, the hot springs team locates an appropriate spring which launches you neatly and precisely up to the edge of *Lava Island*.

There's just one problem: you don't see any *lava*.

You *do* see a lot of ash and igneous rock; there are even what look like gray mountains scattered around. After a while, you make your way to a nearby cluster of mountains only to discover that the valley between them is completely full of large *mirrors*. Most of the mirrors seem to be aligned in a consistent way; perhaps you should head in that direction?

As you move through the valley of mirrors, you find that several of them have fallen from the large metal frames keeping them in place. The mirrors are extremely flat and shiny, and many of the fallen mirrors have lodged into the ash at strange angles. Because the terrain is all one color, it's hard to tell where it's safe to walk or where you're about to run into a mirror.

You note down the patterns of ash (`.`) and rocks (`#`) that you see as you walk (your puzzle input); perhaps by carefully analyzing these patterns, you can figure out where the mirrors are!

For example:

```         
#.##..##. 
..#.##.#. 
##......# 
##......# 
..#.##.#. 
..##..##. 
#.#.##.#. 


#...##..# 
#....#..# 
..##..### 
#####.##. 
#####.##. 
..##..### 
#....#..# 
```

To find the reflection in each pattern, you need to find a perfect reflection across either a horizontal line between two rows or across a vertical line between two columns.

In the first pattern, the reflection is across a vertical line between two columns; arrows on each of the two columns point at the line between the columns:

```         
123456789   
    ><    
#.##..##. 
..#.##.#. 
##......# 
##......# 
..#.##.#. 
..##..##. 
#.#.##.#. 
    ><    
123456789 
```

In this pattern, the line of reflection is the vertical line between columns 5 and 6. Because the vertical line is not perfectly in the middle of the pattern, part of the pattern (column 1) has nowhere to reflect onto and can be ignored; every other column has a reflected column within the pattern and must match exactly: column 2 matches column 9, column 3 matches 8, 4 matches 7, and 5 matches 6.

The second pattern reflects across a horizontal line instead:

```         
1 #...##..# 1 
2 #....#..# 2 
3 ..##..### 3 
4v#####.##.v4 
5^#####.##.^5 
6 ..##..### 6 
7 #....#..# 7 
```

This pattern reflects across the horizontal line between rows 4 and 5. Row 1 would reflect with a hypothetical row 8, but since that's not in the pattern, row 1 doesn't need to match anything. The remaining rows match: row 2 matches row 7, row 3 matches row 6, and row 4 matches row 5.

To *summarize* your pattern notes, add up *the number of columns* to the left of each vertical line of reflection; to that, also add *100 multiplied by the number of rows* above each horizontal line of reflection. In the above example, the first pattern's vertical line has `5` columns to its left and the second pattern's horizontal line has `4` rows above it, a total of *`405`*.

Find the line of reflection in each of the patterns in your notes. *What number do you get after summarizing all of your notes?*

```{python}
import numpy as np

with open('data-2023-13.txt', 'r') as f:
    inp = f.read().split('\n\n')

```

It's not enough to just match two consecutive rows or columns, we need to iterate outwards from each pair that matches. Two consecutive rows the same is a candidate for point of reflection, but not sufficient.

Let's assume that three rows or columns matching is sufficient, or if we do not have enough to check, then that is the match.

```{python}

mirr0 = [j.split('\n') for j in inp]

# loop through and collect
mirr = [np.array([list(i) for i in m]) for m in mirr0]

# len(mirr)

# mirr[3]

for m in mirr: 
    fndr = 0
    fndc = 0
    found = False
    for j in range(len(m)-1): 
        if found: 
            break
        for p,q in zip([0,1,2,3], [1,2,3,4]):
            if found: 
                break
            if j-p >= 0 and j+q < len(m):
                if list(m[j-p]) == list(m[j+q]): 
                    fndr += 1
                    found = True
                    # print(j, p, q, "mirror")
                else: 
                    # this should get us out if it does not match
                    break
            else: 
                # we are out of bounds, and assuming that we have a match
                # there is no way to disprove a match? 
                fndr += 1
                found = True
                # print(j, p, q, "edge")
                
    for k in range(len(m[0])-1): 
        for p,q in zip([0,1,2,3], [1,2,3,4]):
            if k-p >= 0 and k+q < len(m[0]):
                if list(m[:,k-p]) == list(m[:,k+q]): 
                    found = True
                    # keep looking
                else: 
                    # this should get us out if something does not match
                    break
            else: 
                if found == True: 
                    # we've found at least one match
                    fndc += 1
                    break
        # we have gone through the list without a break
        fndc += 1
        break
    
            

                
    # print(fndr, fndc)
    
    
```

That's not really working, let's go back to what I started with which explicitly lists the row differences

```{python}

mirr0 = [j.split('\n') for j in inp]

mirr = [np.array([list(i) for i in m]) for m in mirr0]

for m in mirr: 
    fndr = 0
    fndc = 0
    for j in range(len(m)-1): 
        if list(m[j]) == list(m[j+1]): 
            if j-1 >= 0 and j+2 < len(m):
                if list(m[j-1]) == list(m[j+2]): 
                    if j-2 >= 0 and j+3 < len(m):
                        if list(m[j-2]) == list(m[j+3]):
                            if j-3 >= 0 and j+4 < len(m):
                                if list(m[j-3]) == list(m[j+4]):
                                    if j-4 >= 0 and j+5 < len(m):
                                        if list(m[j-4]) == list(m[j+5]):
                                            fndr += 1
                                    else: 
                                        fndr += 1
                            else: 
                                fndr += 1
                    else: 
                        fndr += 1
            else: 
                fndr += 1

    for k in range(len(m[0])-1): 
        if list(m[:,k]) == list(m[:,k+1]): 
            if k-1 >= 0 and k+2 < len(m[0]):
                if list(m[:,k-1]) == list(m[:,k+2]): 
                    if k-2 >= 0 and k+3 < len(m[0]):
                        if list(m[:,k-2]) == list(m[:,k+3]):
                            if k-3 >= 0 and k+4 < len(m[0]):
                                if list(m[:,k-3]) == list(m[:,k+4]):
                                    if k-4 >= 0 and k+5 < len(m[0]):
                                        if list(m[:,k-4]) == list(m[:,k+5]):
                                            fndc += 1
                                    else: 
                                        fndc += 1
                            else: 
                                fndc += 1
                    else: 
                        fndc += 1
            else: 
                fndc += 1  
              
                
    # print(fndr, fndc)
    if fndc == 2: 
        print(m)
    
```

Revelation: we should only set the mirror row / column when we reach the end. This may not be good for the second part but let's do that for now. There are too many tricky scenarios of *almost* symmetry!

```{python}

mirr0 = [j.split('\n') for j in inp]

# loop through and collect
mirr = [np.array([list(i) for i in m]) for m in mirr0]

summer = 0

for m in mirr: 
    fndr = 0
    fndc = 0
    found = False
    # print(len(m))
    for j in range(len(m)-1): 
        p = 0
        # print('--new row', j)
        while p < 99: 
            if j-p >= 0 and j+p+1 < len(m):
                # print('checking', p)
                if list(m[j-p]) == list(m[j+p+1]): 
                    # print('some match', p)
                    p += 1
                else: 
                    # this should get us out if it does not match
                    # print('no match')
                    break
            else: 
                # we are out of bounds, and assuming that we have a match
                # print('found it')
                fndr += 1
                summer += 100 * (j+1)
                break

    for k in range(len(m[0])-1): 
        p = 0
        while p < 99: 
            if k-p >= 0 and k+p+1 < len(m[0]):
                if list(m[:,k-p]) == list(m[:,k+p+1]): 
                    p += 1
                else: 
                    break
            else: 
                fndc += 1
                summer += (k+1)
                break
  
    # show the results            
    # print(fndr, fndc)
    
 
summer   
    
```

## \-\-- Part Two \-\--

You resume walking through the valley of mirrors and - *SMACK!* - run directly into one. Hopefully nobody was watching, because that must have been pretty embarrassing.

Upon closer inspection, you discover that every mirror has exactly one *smudge*: exactly one `.` or `#` should be the opposite type.

In each pattern, you'll need to locate and fix the smudge that causes a *different reflection line* to be valid. (The old reflection line won't necessarily continue being valid after the smudge is fixed.)

Here's the above example again:

```         
#.##..##. 
..#.##.#. 
##......# 
##......# 
..#.##.#. 
..##..##. 
#.#.##.#.  

#...##..# 
#....#..# 
..##..### 
#####.##. 
#####.##. 
..##..### 
#....#..# 
```

The first pattern's smudge is in the top-left corner. If the top-left `#` were instead `.`, it would have a different, horizontal line of reflection:

```         
1 ..##..##. 1 
2 ..#.##.#. 2 
3v##......#v3 
4^##......#^4 
5 ..#.##.#. 5 
6 ..##..##. 6 
7 #.#.##.#. 7 
```

With the smudge in the top-left corner repaired, a new horizontal line of reflection between rows 3 and 4 now exists. Row 7 has no corresponding reflected row and can be ignored, but every other row matches exactly: row 1 matches row 6, row 2 matches row 5, and row 3 matches row 4.

In the second pattern, the smudge can be fixed by changing the fifth symbol on row 2 from `.` to `#`:

```         
1v#...##..#v1 
2^#...##..#^2 
3 ..##..### 3 
4 #####.##. 4 
5 #####.##. 5 
6 ..##..### 6 
7 #....#..# 7 
```

Now, the pattern has a different horizontal line of reflection between rows 1 and 2.

Summarize your notes as before, but instead use the new different reflection lines. In this example, the first pattern's new horizontal line has 3 rows above it and the second pattern's new horizontal line has 1 row above it, summarizing to the value *`400`*.

In each pattern, fix the smudge and find the different line of reflection. *What number do you get after summarizing the new reflection line in each pattern in your notes?*
