---
title: "Advent of Code 2023 Day 3"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 3: Gear Ratios \-\--

You and the Elf eventually reach a [gondola lift](https://en.wikipedia.org/wiki/Gondola_lift) station; he says the gondola lift will take you up to the *water source*, but this is as far as he can bring you. You go inside.

It doesn't take long to find the gondolas, but there seems to be a problem: they're not moving.

"Aaah!"

You turn around to see a slightly-greasy Elf with a wrench and a look of surprise. "Sorry, I wasn't expecting anyone! The gondola lift isn't working right now; it'll still be a while before I can fix it." You offer to help.

The engineer explains that an engine part seems to be missing from the engine, but nobody can figure out which one. If you can *add up all the part numbers* in the engine schematic, it should be easy to work out which part is missing.

The engine schematic (your puzzle input) consists of a visual representation of the engine. There are lots of numbers and symbols you don't really understand, but apparently *any number adjacent to a symbol*, even diagonally, is a "part number" and should be included in your sum. (Periods (`.`) do not count as a symbol.)

Here is an example engine schematic:

```         
467..114.. 
...*...... 
..35..633. 
......#... 
617*...... 
.....+.58. 
..592..... 
......755. 
...$.*.... 
.664.598.. 
```

In this schematic, two numbers are *not* part numbers because they are not adjacent to a symbol: `114` (top right) and `58` (middle right). Every other number is adjacent to a symbol and so *is* a part number; their sum is *`4361`*.

Of course, the actual engine schematic is much larger. *What is the sum of all of the part numbers in the engine schematic?*

```{python}

with open('data-2023-03.txt', 'r') as f:
    inp = f.read().splitlines()

len(inp)
len(inp[0])
```

Let's find the possible symbols, that should be easier than regex, maybe?

```{python}
# here's another python cell for good luck

charact = ''.join(inp)

sc = sorted(list(set(charact)))

# just do it manually
sym = '#$%&*+-/=@'

num = '0123456789'
```

Create an array with the schematic input, but we want to have `.` characters on the outside so that we can loop more easily i.e. not have to worry if we're on an edge.

```{python}
import numpy as np
import itertools

# array full of dots
arr = np.full((142, 142), '.')

# list of lists
inp_char = [list(x) for x in inp]

# put the input into the array
arr[1:141, 1:141] = inp_char

# check 
# arr[1, 59]

```

```{python}

summer = 0
i = 0

while i < arr.shape[1]: 
    j = 0
    while j < arr.shape[0]:
        # reset these through each loop
        sym_found = False
        curr_num = ''
        # test the current character
        if arr[i,j] == '.':
            # do nothing
            j += 1
        elif arr[i,j] in sym: 
            # do nothing
            j += 1
        elif arr[i,j] in num: 
            # record the number
            curr_num += arr[i,j]
            # print(arr[i,j])
            # search for symbols
            for m,n in itertools.product([-1, 0, 1], [-1, 0, 1]):
                if arr[i+m,j+n] in sym: 
                    sym_found = True
            # increase the position in our row
            j += 1
            if arr[i,j] in num:
                curr_num += arr[i,j]
                for m,n in itertools.product([-1, 0, 1], [-1, 0, 1]):
                    if arr[i+m,j+n] in sym:
                        sym_found = True
                # increase row position again
                j += 1
                if arr[i,j] in num: 
                    curr_num += arr[i,j]
                    for m,n in itertools.product([-1, 0, 1], [-1, 0, 1]):
                        if arr[i+m,j+n] in sym:
                            sym_found = True
                    # increase row position again
                    j += 1
            # if there is a symbol, add the number to the sum
            if sym_found == True: 
                summer += int(curr_num)
                # print(curr_num)
    # iterate i when we reach the end of j
    i += 1
        
summer

```

## \-\-- Part Two \-\--

The engineer finds the missing part and installs it in the engine! As the engine springs to life, you jump in the closest gondola, finally ready to ascend to the water source.

You don't seem to be going very fast, though. Maybe something is still wrong? Fortunately, the gondola has a phone labeled "help", so you pick it up and the engineer answers.

Before you can explain the situation, she suggests that you look out the window. There stands the engineer, holding a phone in one hand and waving with the other. You're going so slowly that you haven't even left the station. You exit the gondola.

The missing part wasn't the only issue - one of the gears in the engine is wrong. A *gear* is any `*` symbol that is adjacent to *exactly two part numbers*. Its *gear ratio* is the result of multiplying those two numbers together.

This time, you need to find the gear ratio of every gear and add them all up so that the engineer can figure out which gear needs to be replaced.

Consider the same engine schematic again:

```         
467..114.. 
...*...... 
..35..633. 
......#... 
617*...... 
.....+.58. 
..592..... 
......755. 
...$.*.... 
.664.598.. 
```

In this schematic, there are *two* gears. The first is in the top left; it has part numbers `467` and `35`, so its gear ratio is `16345`. The second gear is in the lower right; its gear ratio is `451490`. (The `*` adjacent to `617` is *not* a gear because it is only adjacent to one part number.) Adding up all of the gear ratios produces *`467835`*.

*What is the sum of all of the gear ratios in your engine schematic?*

Now we are looking for all of the `*` symbols and checking for surrounding numbers. We need to be more careful since we are looking for exactly two adjacent strings of numbers, so we need to know where those numbers start and finish.

```{python}

# change symbol input, we actually care about the * now
sym = '#$%&+-/=@'

summer = 0
i = 0

while i < arr.shape[1]: 
    j = 0
    while j < arr.shape[0]:
        # reset these through each loop
        nf = ''
        row_above = False
        row_below = False
        # test the current character
        if arr[i,j] == '.' or arr[i,j] in sym or arr[i,j] in num:
            # do nothing
            j += 1
        elif arr[i,j] == '*': 
            # we have found a gear if we have also found two numbers. 
            # in the row above and below, we could go from j-3 to j+3
            # there could also be two numbers in that range
            # in the same row as * we have j-3 to j+3
            # but we know those are different numbers
                    
            # look to the left of the *
            if arr[i,j-1] in num:
                if arr[i,j-2] in num: 
                    if arr[i,j-3] in num: 
                        nf += arr[i,j-3] + arr[i,j-2] + arr[i,j-1] + ' '
                    else: 
                        nf += arr[i,j-2] + arr[i,j-1] + ' '
                else: 
                    nf += arr[i,j-1]
                    
            # look to the right of the *
            if arr[i,j+1] in num:
                if arr[i,j+2] in num: 
                    if arr[i,j+3] in num:
                        nf += arr[i,j+1] + arr[i,j+2] + arr[i,j+3] + ' '
                    else: 
                        nf += arr[i,j+1] + arr[i,j+2] + ' '
                else: 
                    nf += arr[i,j+1] + ' '
            
            # look above the *
            if arr[i-1,j] in num: 
                # backwards then forwards
                row_above = True
                if arr[i-1,j-1] in num:
                    if arr[i-1,j-2] in num: 
                        nf += arr[i-1,j-2] + arr[i-1,j-1] + arr[i-1,j] + ' '
                    else: 
                        if arr[i-1,j+1] in num: 
                            nf += arr[i-1,j-1] + arr[i-1,j] + arr[i-1,j+1] + ' '
                        else: 
                            nf += arr[i-1,j-1] + arr[i-1,j] + ' '
                else: 
                    if arr[i-1,j+1] in num:
                        if arr[i-1,j+2] in num:
                            nf += arr[i-1,j] + arr[i-1,j+1] + arr[i-1,j+2] + ' '
                        else: 
                            nf += arr[i-1,j] + arr[i-1,j+1] + ' '
                    else: 
                        nf += arr[i-1,j] + ' '
                            
            # look up and left
            if not row_above and arr[i-1,j-1] in num: 
                # look backwards
                if arr[i-1,j-2] in num: 
                    if arr[i-1,j-3] in num: 
                        nf += arr[i-1,j-3] + arr[i-1,j-2] + arr[i-1,j-1] + ' '
                    else: 
                        nf += arr[i-1,j-2] + arr[i-1,j-1] + ' '
                else: 
                    nf += arr[i-1,j-1] + ' '
                    
            # look up and right
            if not row_above and arr[i-1,j+1] in num: 
                # look forwards
                if arr[i-1,j+2] in num: 
                    if arr[i-1,j+3] in num: 
                        nf += arr[i-1,j+1] + arr[i-1,j+2] + arr[i-1,j+3] + ' '
                    else: 
                        nf += arr[i-1,j+1] + arr[i-1,j+2] + ' '
                else: 
                    nf += arr[i-1,j+1] + ' '
                
            # look below the *
            if arr[i+1,j] in num: 
                # backwards then forwards
                row_below = True
                if arr[i+1,j-1] in num:
                    if arr[i+1,j-2] in num: 
                        nf += arr[i+1,j-2] + arr[i+1,j-1] + arr[i+1,j] + ' '
                    else: 
                        if arr[i+1,j+1] in num: 
                            nf += arr[i+1,j-1] + arr[i+1,j] + arr[i+1,j+1] + ' '
                        else: 
                            nf += arr[i+1,j-1] + arr[i+1,j] + ' '
                else: 
                    if arr[i+1,j+1] in num:
                        if arr[i+1,j+2] in num:
                            nf += arr[i+1,j] + arr[i+1,j+1] + arr[i+1,j+2] + ' '
                        else: 
                            nf += arr[i+1,j] + arr[i+1,j+1] + ' '
                    else: 
                        nf += arr[i+1,j] + ' '
                
            if not row_below and arr[i+1,j-1] in num: 
                # look backwards
                if arr[i+1,j-2] in num: 
                    if arr[i+1,j-3] in num: 
                        nf += arr[i+1,j-3] + arr[i+1,j-2] + arr[i+1,j-1] + ' '
                    else: 
                        nf += arr[i+1,j-2] + arr[i+1,j-1] + ' '
                else: 
                    nf += arr[i+1,j-1] + ' '
              
            if not row_below and arr[i+1,j+1] in num:
                # look forwards
                if arr[i+1,j+2] in num: 
                    if arr[i+1,j+3] in num: 
                        nf += arr[i+1,j+1] + arr[i+1,j+2] + arr[i+1,j+3] + ' '
                    else: 
                        nf += arr[i+1,j+1] + arr[i+1,j+2] + ' '
                else: 
                    nf += arr[i+1,j+1] + ' '
                
              
            # now do something with this information
            # print(nf)
            yy = nf.split()
            if len(yy) == 2:
                summer += int(yy[0]) * int(yy[1])
            j += 1
    # iterate i when we reach the end of j
    i += 1
      

summer
```

First answer: 64,491,217 (too low)

Second: 24,397,395 (too low)

Third: 75,847,567 (gold star)
