---
title: "Advent of Code 2023 Day 1"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 1: Trebuchet?! \-\--

Something is wrong with global snow production, and you've been selected to take a look. The Elves have even given you a map; on it, they've used stars to mark the top fifty locations that are likely to be having problems.

You've been doing this long enough to know that to restore snow operations, you need to check all *fifty stars* by December 25th.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants *one star*. Good luck!

You try to ask why they can't just use a [weather machine](https://adventofcode.com/2015/day/1) ("not powerful enough") and where they're even sending you ("the sky") and why your map looks mostly blank ("you sure ask a lot of questions") and hang on did you just say the sky ("of course, where do you think snow comes from") when you realize that the Elves are already loading you into a [trebuchet](https://en.wikipedia.org/wiki/Trebuchet) ("please hold still, we need to strap you in").

As they're making the final adjustments, they discover that their calibration document (your puzzle input) has been *amended* by a very young Elf who was apparently just excited to show off her art skills. Consequently, the Elves are having trouble reading the values on the document.

The newly-improved calibration document consists of lines of text; each line originally contained a specific *calibration value* that the Elves now need to recover. On each line, the calibration value can be found by combining the *first digit* and the *last digit* (in that order) to form a single *two-digit number*.

For example:

```         
1abc2 
pqr3stu8vwx 
a1b2c3d4e5f 
treb7uchet 
```

In this example, the calibration values of these four lines are `12`, `38`, `15`, and `77`. Adding these together produces *`142`*.

Consider your entire calibration document. *What is the sum of all of the calibration values?*

```{python}

with open('data-2023-01.txt', 'r') as f:
    inp = f.read().splitlines()

```

Find the first and last digit in a string. We could use `re` or split the string with list comprehension.

```{python}
# let's try regex first
import re

get_digi = [re.findall('\d', x) for x in inp]

double_digi = [int(x[0])*10 + int(x[-1]) for x in get_digi]

sum(double_digi)
```

This could work with splitting a string forwards and backwards, and is more like what I think part 2 will be which is including the numbers as words.

```{python}

first_digi = []
last_digi = []

for i in inp:
    for s in str(i): 
        if s.isdigit(): 
            first_digi.append(int(s))
            break
    for s in i[::-1]:
        if s.isdigit():
            last_digi.append(int(s))
            break

double_digi_1 = [f*10+l for f,l in zip(first_digi, last_digi)]

sum(double_digi_1)
```

## \-\-- Part Two \-\--

Your calculation isn't quite right. It looks like some of the digits are actually *spelled out with letters*: `one`, `two`, `three`, `four`, `five`, `six`, `seven`, `eight`, and `nine` *also* count as valid "digits".

Equipped with this new information, you now need to find the real first and last digit on each line. For example:

```         
two1nine eightwothree abcone2threexyz xtwone3four 4nineeightseven2 zoneight234 7pqrstsixteen 
```

In this example, the calibration values are `29`, `83`, `13`, `24`, `42`, `14`, and `76`. Adding these together produces *`281`*.

*What is the sum of all of the calibration values?*

I think I want to make a function first to return the digit found, that'll be much nicer in the long run for the loop of input.

```{python}

def get_first(ss):
    """Get the first digit, numeric or spelled, from the input string ss"""
    # define dict for values
    nums = {'one': 1, 
            'two': 2, 
            'three': 3, 
            'four': 4, 
            'five': 5, 
            'six': 6, 
            'seven': 7, 
            'eight': 8, 
            'nine': 9,
            }

    # loop through the input
    for s in range(len(ss)): 
        # simplest case first, we've found an actual digit
        if ss[s].isdigit(): 
            return int(ss[s])
        for k,v in nums.items(): 
            if ss[s:s+len(k)] == k:
                return v
 
def get_last(ss):
    """
    Get the LAST digit, numeric or spelled, from the input string ss
    The input string is already reversed, so we need to reverse our numbers
    """
    # define dict for values
    nums = {'eno': 1, 
            'owt': 2, 
            'eerht': 3, 
            'ruof': 4, 
            'evif': 5, 
            'xis': 6, 
            'neves': 7, 
            'thgie': 8, 
            'enin': 9,
            }

    # loop through the input
    for s in range(len(ss)): 
        # simplest case first, we've found an actual digit
        if ss[s].isdigit(): 
            return int(ss[s])
        for k,v in nums.items(): 
            if ss[s:s+len(k)] == k:
                return v       
```

Now do the searching and gathering

```{python}

first_digi = []
last_digi = []

for i in inp:
    first_digi.append(get_first(i))
    last_digi.append(get_last(i[::-1]))

double_digi_2 = [f*10+l for f,l in zip(first_digi, last_digi)]

sum(double_digi_2)
```
