---
title: "Advent of Code 2023 Day 18"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 18: Lavaduct Lagoon \-\--

Thanks to your efforts, the machine parts factory is one of the first factories up and running since the lavafall came back. However, to catch up with the large backlog of parts requests, the factory will also need a *large supply of lava* for a while; the Elves have already started creating a large lagoon nearby for this purpose.

However, they aren't sure the lagoon will be big enough; they've asked you to take a look at the *dig plan* (your puzzle input). For example:

```         
R 6 (#70c710) 
D 5 (#0dc571) 
L 2 (#5713f0) 
D 2 (#d2c081) 
R 2 (#59c680) 
D 2 (#411b91) 
L 5 (#8ceee2) 
U 2 (#caa173) 
L 1 (#1b58a2) 
U 2 (#caa171) 
R 2 (#7807d2) 
U 3 (#a77fa3) 
L 2 (#015232) 
U 2 (#7a21e3) 
```

The digger starts in a 1 meter cube hole in the ground. They then dig the specified number of meters *up* (`U`), *down* (`D`), *left* (`L`), or *right* (`R`), clearing full 1 meter cubes as they go. The directions are given as seen from above, so if "up" were north, then "right" would be east, and so on. Each trench is also listed with *the color that the edge of the trench should be painted* as an [RGB hexadecimal color code](https://en.wikipedia.org/wiki/RGB_color_model#Numeric_representations).

When viewed from above, the above example dig plan would result in the following loop of *trench* (`#`) having been dug out from otherwise *ground-level terrain* (`.`):

```         
####### 
#.....# 
###...# 
..#...# 
..#...# 
###.### 
#...#.. 
##..### 
.#....# 
.###### 
```

At this point, the trench could contain 38 cubic meters of lava. However, this is just the edge of the lagoon; the next step is to *dig out the interior* so that it is one meter deep as well:

```         
####### 
####### 
####### 
..##### 
..##### 
####### 
#####.. 
####### 
.###### 
.###### 
```

Now, the lagoon can contain a much more respectable *`62`* cubic meters of lava. While the interior is dug out, the edges are also painted according to the color codes in the dig plan.

The Elves are concerned the lagoon won't be large enough; if they follow their dig plan, *how many cubic meters of lava could it hold?*

```{python}

with open('data-2023-18.txt', 'r') as f:
    inp = f.read().splitlines()

```

Parse the input then fill in a numpy array to do the digging

```{python}

# tracking
x = 0
y = 0
maxx = 0
maxy = 0
minx = 0
miny = 0


# moves for part 1
p1 = [x.split() for x in inp]

for p in p1:
    # number of moves
    n = int(p[1])
    # directions
    if p[0] == 'R': 
        x += n
    elif p[0] == 'L': 
        x -= n
    elif p[0] == 'D': 
        y += n
    elif p[0] == 'U': 
        y -= n
    # check on max
    if x > maxx: 
        maxx = x
    if y > maxy: 
        maxy = y
    if x < minx: 
        minx = x
    if y < miny: 
        miny = y
      
maxx, maxy, minx, miny

maxx - minx, maxy - miny
```

Let's use that for the array size

```{python}
import numpy as np
import csv

lava = np.zeros((500, 500), dtype=int)

# tracking
x = 250
y = 250

lava[x,y] = 1

for p in p1:
    # number of moves
    n = int(p[1])
    # directions
    if p[0] == 'R': 
        for s in range(n):
            y += 1
            lava[x,y] = 1
    elif p[0] == 'L': 
        for s in range(n):
            y -= 1
            lava[x,y] = 1
    elif p[0] == 'D': 
        for s in range(n):
            x += 1
            lava[x,y] = 1
    elif p[0] == 'U': 
        for s in range(n):
            x -= 1
            lava[x,y] = 1

summer = 0
for l in lava[195:201]: 
    # print(''.join(str(l[0:500])))
    # print(sum(l))
    summer += sum(l)

# summer

np.savetxt('data-2023-18-out.csv', lava, delimiter=',', fmt='%d')

```

Doesn't have to be a separate cell but feels like a different step in the procedure: loop through and add ones into the array for filled in lava lake.

```{python}


for x, l in enumerate(lava): 
    # keep track of if we are on or off, always starts off
    dug = False
    lock = False
    for y, v in enumerate(l):
        if dug == False: 
            if lava[x,y] == 1 and lava[x,y+1] == 0:  
                # we are starting a dig out between trenches
                dug = True
                lock = False
            elif lava[x,y] == 1 and lava[x,y+1] == 1: 
                # we are on the edge of a trench
                dug = True
                lock = True
            elif v == 0: 
                # we are off and want to stay off
                pass
        else: 
            # dug == True
            if lock == False: 
                if lava[x,y] == 1 and lava[x,y+1] == 0: 
                    # the end of the trench, turn off digging
                    dug = False
                elif lava[x,y] == 1 and lava[x,y+1] == 1: 
                    # the end of the trench, turn off digging
                    lock = True                  
                else: 
                    # current value is 1 or 0, within 
                    lava[x,y] = 1
            else: 
                # lock = True, along the edge
                if lava[x,y] == 1 and lava[x,y+1] == 0:
                    # going into the space that needs to be dug
                    lock = False
                
                
summer = 0
for l in lava[195:201]: 
    # print(''.join(str(l[0:500])))
    # print(sum(l))
    summer += sum(l)

summer  

# 188696 too high  
# manual colouring in a spreadsheet
# 46338 too high
# 46334 correct
  
```

## \-\-- Part Two \-\--

The Elves were right to be concerned; the planned lagoon would be *much too small*.

After a few minutes, someone realizes what happened; someone *swapped the color and instruction parameters* when producing the dig plan. They don't have time to fix the bug; one of them asks if you can *extract the correct instructions* from the hexadecimal codes.

Each hexadecimal code is *six hexadecimal digits* long. The first five hexadecimal digits encode the *distance in meters* as a five-digit hexadecimal number. The last hexadecimal digit encodes the *direction to dig*: `0` means `R`, `1` means `D`, `2` means `L`, and `3` means `U`.

So, in the above example, the hexadecimal codes can be converted into the true instructions:

-   `#70c710` = `R 461937`

-   `#0dc571` = `D 56407`

-   `#5713f0` = `R 356671`

-   `#d2c081` = `D 863240`

-   `#59c680` = `R 367720`

-   `#411b91` = `D 266681`

-   `#8ceee2` = `L 577262`

-   `#caa173` = `U 829975`

-   `#1b58a2` = `L 112010`

-   `#caa171` = `D 829975`

-   `#7807d2` = `L 491645`

-   `#a77fa3` = `U 686074`

-   `#015232` = `L 5411`

-   `#7a21e3` = `U 500254`

Digging out this loop and its interior produces a lagoon that can hold an impressive *`952408144115`* cubic meters of lava.

Convert the hexadecimal color codes into the correct instructions; if the Elves follow this new dig plan, *how many cubic meters of lava could the lagoon hold?*

```{python}

# parse some hex digits
ph = [x.split()[2] for x in inp]

p2 = [x.replace('(', '').replace(')', '').replace('#', '') for x in ph]

def get_direct(h): 
    # The last hexadecimal digit encodes the direction to dig: 
    # 0 means R, 1 means D, 2 means L, and 3 means U.
    dirs = {'0': 'R', '1': 'D', '2': 'L', '3': 'U'}
    return dirs[h[-1]]
  
pd = [[get_direct(x), int(x[:5], 16)] for x in p2]
    

```
