---
title: "Advent of Code 2023 Day 2"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 2: Cube Conundrum \-\--

You're launched high into the atmosphere! The apex of your trajectory just barely reaches the surface of a large island floating in the sky. You gently land in a fluffy pile of leaves. It's quite cold, but you don't see much snow. An Elf runs over to greet you.

The Elf explains that you've arrived at *Snow Island* and apologizes for the lack of snow. He'll be happy to explain the situation, but it's a bit of a walk, so you have some time. They don't get many visitors up here; would you like to play a game in the meantime?

As you walk, the Elf shows you a small bag and some cubes which are either red, green, or blue. Each time you play this game, he will hide a secret number of cubes of each color in the bag, and your goal is to figure out information about the number of cubes.

To get information, once a bag has been loaded with cubes, the Elf will reach into the bag, grab a handful of random cubes, show them to you, and then put them back in the bag. He'll do this a few times per game.

You play several games and record the information from each game (your puzzle input). Each game is listed with its ID number (like the `11` in `Game 11: ...`) followed by a semicolon-separated list of subsets of cubes that were revealed from the bag (like `3 red, 5 green, 4 blue`).

For example, the record of a few games might look like this:

```         
Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green 
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue 
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red 
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red 
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green 
```

In game 1, three sets of cubes are revealed from the bag (and then put back again). The first set is 3 blue cubes and 4 red cubes; the second set is 1 red cube, 2 green cubes, and 6 blue cubes; the third set is only 2 green cubes.

The Elf would first like to know which games would have been possible if the bag contained *only 12 red cubes, 13 green cubes, and 14 blue cubes*?

In the example above, games 1, 2, and 5 would have been *possible* if the bag had been loaded with that configuration. However, game 3 would have been *impossible* because at one point the Elf showed you 20 red cubes at once; similarly, game 4 would also have been *impossible* because the Elf showed you 15 blue cubes at once. If you add up the IDs of the games that would have been possible, you get *`8`*.

Determine which games would have been possible if the bag had been loaded with only 12 red cubes, 13 green cubes, and 14 blue cubes. *What is the sum of the IDs of those games?*

```{python}

with open('data-2023-02.txt', 'r') as f:
    inp = f.read().splitlines()

```

Create a nice dict / list structure for easy iteration. I'm not sure what part two will be so let us set ourselves up for success. Overall it's a dictionary with the game number as keys, then lists of dictionaries for each draw for each game.

```{python}
import re

# here's another python cell for good luck
games = {i.split(':')[0]: i.split(':')[1].split(';') for i in inp}

# check the structure
# games['Game 1']

# create dict to build on
game_dict = dict()

# loop through the dictionary
for k,v in games.items():
    # get the key for the game as number
    z = re.findall('\\d+', k)[0]
    # an empty list for the dict
    game_dict[z] = []
    # loop through the values in the original list
    for d in v: 
        # print(d)
        # turn each of these into a dictionary
        game_dict[z].append( 
            {re.findall('[a-z]+', y)[0]: int(re.findall('\d+', y)[0])
            for y in d.split(',')}
            )

game_dict['1']    
```

Okay, now that the building of the hopefully nice structure is done after much too long, let's look for good games.

```{python}
# 12 red cubes, 13 green cubes, and 14 blue cubes
lims = {'red': 12, 'green': 13, 'blue': 14}
counter = 0

# loop through the games
for k,v in game_dict.items():
    found = False
    # loop through the dicts
    for d in v: 
        # print(d)
        # loop through the elements in the dict
        for g,h in d.items(): 
            # if we are in an impossible game
            if h > lims[g]: 
                # print(d)
                # print(k)
                counter += int(k)
                found = True
                break
    # the first break gets out of the d.items() loop, this gets us out of v
        if found == True:
            break

# turns out I'm counting impossible games and we want possible games   
# using ramanujan to get the total of 100 games = (n+1)*(n/2)
101*50-counter

            
    
```

## \-\-- Part Two \-\--

The Elf says they've stopped producing snow because they aren't getting any *water*! He isn't sure why the water stopped; however, he can show you how to get to the water source to check it out for yourself. It's just up ahead!

As you continue your walk, the Elf poses a second question: in each game you played, what is the *fewest number of cubes of each color* that could have been in the bag to make the game possible?

Again consider the example games from earlier:

```         
Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green 
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue 
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red 
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red 
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green 
```

-   In game 1, the game could have been played with as few as 4 red, 2 green, and 6 blue cubes. If any color had even one fewer cube, the game would have been impossible.

-   Game 2 could have been played with a minimum of 1 red, 3 green, and 4 blue cubes.

-   Game 3 must have been played with at least 20 red, 13 green, and 6 blue cubes.

-   Game 4 required at least 14 red, 3 green, and 15 blue cubes.

-   Game 5 needed no fewer than 6 red, 3 green, and 2 blue cubes in the bag.

The *power* of a set of cubes is equal to the numbers of red, green, and blue cubes multiplied together. The power of the minimum set of cubes in game 1 is `48`. In games 2-5 it was `12`, `1560`, `630`, and `36`, respectively. Adding up these five powers produces the sum *`2286`*.

For each game, find the minimum set of cubes that must have been present. *What is the sum of the power of these sets?*

```{python}

# create a nice dict to hold the minimum numbers
min_dice = {str(x): {'red': 0, 'green': 0, 'blue': 0} for x in range(1, 101)}

# loop through the games
for k,v in game_dict.items():
    # loop through the dicts
    for d in v: 
        # print(d)
        # loop through the elements in the dict
        for g,h in d.items(): 
            # print(g)
            if h > min_dice[k][g]:
                min_dice[k][g] = h
    # print(min_dice[k])

sum([n['red'] * n['green'] * n['blue'] for m,n in min_dice.items()])



```
