---
title: "Advent of Code 2024"
---

## Solutions for 2024

[Day 1](2024-01.qmd)

1.  Parse the input and find the difference and add them up
2.  Some numbers appear in both lists, so calculate a similarity score

-   Nice easy introduction for day 1
-   Getting the input in the right shape was easy
-   Pre-calculate part two with collections.Counter rather than counting each time

[Day 2](2024-02.qmd)

1.  Check to see if the reports are all increasing or decreasing
2.  Check the reports, but with the ability to remove one value

-   Make a function and loop through the input
-   Use the same function, but with another function to edit possible input

[Day 3](2024-03.qmd)

1.  Find the sum of the multiply statements - but find them first
2.  There's a switch that turns the statements on and off

-   Regex only on day 3. Find the mul() statements, then evaluate them
-   Find the do() and don't() statements as well, then iterate

[Day 4](2024-04.qmd)

1.  Do a word search for XMAS
2.  Actually search for MAS in in X shape

-   Iterate for X and then go for different directions
-   Iterate for A and then go for different directions

[Day 5](2024-05.qmd)

1.  Sum up the middle value of the updates that are in the correct order
2.  Sort the bad updates into the correct order and sum the middle values

-   Loop through the lists and if subsequent numbers are in the correct order, the whole list is in order
-   For the bad lists, place the pieces in the correct order, then sum up. More difficult than it sounds

[Day 6](2024-06.qmd)

1.  
2.  

-   
-   


[Day 7](2024-07.qmd)

1.  
2.  

-   
-   


[Day 8](2024-08.qmd)

1.  
2.  

-   
-   


[Day 9](2024-09.qmd)

1.  
2.  

-   
-   


[Day 10](2024-10.qmd)

1.  
2.  

-   
-   


[Day 11](2024-11.qmd)

1.  
2.  

-   
-   


[Day 12](2024-12.qmd)

1.  
2.  

-   
-   


[Day 13](2024-13.qmd)

1.  
2.  

-   
-   


[Day 14](2024-14.qmd)

1.  
2.  

-   
-   


[Day 15](2024-15.qmd)

1.  
2.  

-   
-   


[Day 16](2024-16.qmd)

1.  
2.  

-   
-   


[Day 17](2024-17.qmd)

1.  
2.  

-   
-   


[Day 18](2024-18.qmd)

1.  
2.  

-   
-   


[Day 19](2024-19.qmd)

1.  
2.  

-   
-   


[Day 20](2024-20.qmd)

1.  
2.  

-   
-   


[Day 21](2024-21.qmd)

1.  
2.  

-   
-   


[Day 22](2024-22.qmd)

1.  
2.  

-   
-   


[Day 23](2024-23.qmd)

1.  
2.  

-   
-   


[Day 24](2024-24.qmd)

1.  
2.  

-   
-   


[Day 25](2024-25.qmd)

1.  
2.  

-   
-   

