---
title: "Advent of Code 2015 Day 20"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 20: Infinite Elves and Infinite Houses \-\--

To keep the Elves busy, Santa has them deliver some presents by hand, door-to-door. He sends them down a street with infinite houses numbered sequentially: `1`, `2`, `3`, `4`, `5`, and so on.

Each Elf is assigned a number, too, and delivers presents to houses based on that number:

-   The first Elf (number `1`) delivers presents to every house: `1`, `2`, `3`, `4`, `5`, ....

-   The second Elf (number `2`) delivers presents to every second house: `2`, `4`, `6`, `8`, `10`, ....

-   Elf number `3` delivers presents to every third house: `3`, `6`, `9`, `12`, `15`, ....

There are infinitely many Elves, numbered starting with `1`. Each Elf delivers presents equal to *ten times* his or her number at each house.

So, the first nine houses on the street end up like this:

    House 1 got 10 presents.
    House 2 got 30 presents.
    House 3 got 40 presents.
    House 4 got 70 presents.
    House 5 got 60 presents.
    House 6 got 120 presents.
    House 7 got 80 presents.
    House 8 got 150 presents.
    House 9 got 130 presents.

The first house gets `10` presents: it is visited only by Elf `1`, which delivers `1 * 10 = 10` presents. The fourth house gets `70` presents, because it is visited by Elves `1`, `2`, and `4`, for a total of `10 + 20 + 40 = 70` presents.

What is the *lowest house number* of the house to get at least as many presents as the number in your puzzle input?

Your puzzle input is `29000000`.

```{python}

presents = 29000000

```

I think we just have to loop

```{python}

house = 600000
tot = 0

while tot < presents:
    # increment house visited
    house += 100
    # always start with elf 1
    tot = 10   
    # if even, then go through everything
    if house % 2 == 0:
        for h in range(house, 1, -1):
            if house % h == 0:
                tot += 10 * h
    else: 
        # odd number, we can just go through odds
        for h in range(house, 1, -2):
            if house % h == 0:
                tot += 10 * h
    # print(tot)

tot
house

```

Steps of 10000: 29295310, 810000

From 500,000, steps of 1,000: 29203200, 693000

From 600,000, steps of 100: 29203200, 693000

I think I want to try this somewhat differently, counting down.

```{python}

house = 700000
tot = 0


while house > 600000:
    # increment house visited
    house -= 10
    # always start with elf 1
    tot = 10   
    # if even, then go through everything
    if house % 2 == 0:
        for h in range(house, 1, -1):
            if house % h == 0:
                tot += 10 * h
    else: 
        # odd number, we can just go through odds
        for h in range(house, 1, -2):
            if house % h == 0:
                tot += 10 * h
    if tot > presents: 
        print(tot)
        print(house)


tot
house
```

`29030400, 695520`

`29203200, 693000`

`29260800, 665280`

Let's look for factors instead

https://stackoverflow.com/questions/6800193/what-is-the-most-efficient-way-of-finding-all-the-factors-of-a-number-in-python

```{python}

from functools import reduce

def factors(n):    
    return set(reduce(list.__add__, 
                ([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0)))

```

```{python}


for i in range(600000, 700000):
    x = sum(factors(i)) * 10
    if x > presents:
        print(x)
        print(i)
        break

```

## \-\-- Part Two \-\--

The Elves decide they don't want to visit an infinite number of houses. Instead, each Elf will stop after delivering presents to `50` houses. To make up for it, they decide to deliver presents equal to *eleven times* their number at each house.

With these changes, what is the new *lowest house number* of the house to get at least as many presents as the number in your puzzle input?

```{python}


def factors2(n):    
    tmp = reduce(list.__add__, ([i, n//i] 
          for i in range(1, int(n**0.5) + 1) if n % i == 0))
    return set([t for t in tmp if t >= (n/50)])

```

```{python}

mx = 0

for i in range(665280, 750000, 1):
    x = sum(factors2(i)) * 11
    if x > mx:
        mx = x
        print(x)
        print(i)
        

```

705600 is the correct answer
