---
title: "Advent of Code 2015 Day 15"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 15: Science for Hungry People \-\--

Today, you set out on the task of perfecting your milk-dunking cookie recipe. All you have to do is find the right balance of ingredients.

Your recipe leaves room for exactly `100` teaspoons of ingredients. You make a list of the *remaining ingredients you could use to finish the recipe* (your puzzle input) and their *properties per teaspoon*:

-   `capacity` (how well it helps the cookie absorb milk)

-   `durability` (how well it keeps the cookie intact when full of milk)

-   `flavor` (how tasty it makes the cookie)

-   `texture` (how it improves the feel of the cookie)

-   `calories` (how many calories it adds to the cookie)

You can only measure ingredients in whole-teaspoon amounts accurately, and you have to be accurate so you can reproduce your results in the future. The *total score* of a cookie can be found by adding up each of the properties (negative totals become `0`) and then multiplying together everything except calories.

For instance, suppose you have these two ingredients:

    Butterscotch: capacity -1, durability -2, flavor 6, texture 3, calories 8
    Cinnamon: capacity 2, durability 3, flavor -2, texture -1, calories 3

Then, choosing to use `44` teaspoons of butterscotch and `56` teaspoons of cinnamon (because the amounts of each ingredient must add up to `100`) would result in a cookie with the following properties:

-   A `capacity` of `44*-1 + 56*2 = 68`

-   A `durability` of `44*-2 + 56*3 = 80`

-   A `flavor` of `44*6 + 56*-2 = 152`

-   A `texture` of `44*3 + 56*-1 = 76`

Multiplying these together (`68 * 80 * 152 * 76`, ignoring `calories` for now) results in a total score of `62842880`, which happens to be the best score possible given these ingredients. If any properties had produced a negative total, it would have instead become zero, causing the whole score to multiply to zero.

Given the ingredients in your kitchen and their properties, what is the *total score* of the highest-scoring cookie you can make?

```{python}

with open('data-2015-15.txt', 'r') as f:
    inp = f.read().splitlines()

```

`split()` this into dictionaries

```{python}

# lists to start
ingr = [x.split(':') for x in inp]

print(ingr)

# dictionary, probably
ing = {x[0]: x[1].split(',') for x in ingr}

for k,v in ing.items():
    ing[k] = {}
    for x in [m.strip() for m in v]:
        a,b = x.split()
        ing[k].update({a: int(b)})


print()
print(ing)
```

That may have been too much, but there it is.

Now we need to know how much of each thing to include in our cookies.

How many ways are there to have four ingredients that add to 100?

```{python}
import itertools

counter = []

for g,h,i,j in itertools.product(range(101),
                                 range(101),
                                 range(101),
                                 range(101)):
    if g + h + i + j == 100:
        counter.append([g,h,i,j])

len(counter)
```

Sweet! Hopefully, we want to make delicious cookies.

```{python}

score = 0

ings = list(ing.keys())
prop = list(ing['Sprinkles'].keys())[:-1]

for c in counter:
    s = [0,0,0,0]
    for e,i in enumerate(ings):
        for f,p in enumerate(prop):
            s[f] += ing[i][p] * c[e]
            
    sc = max(0,s[0]) * max(0,s[1]) * max(0,s[2]) * max(0,s[3])
    if sc > score:
        # print(sc)
        # print(s)
        score = sc

print(score)
```

## \-\-- Part Two \-\--

Your cookie recipe becomes wildly popular! Someone asks if you can make another recipe that has exactly `500` calories per cookie (so they can use it as a meal replacement). Keep the rest of your award-winning process the same (100 teaspoons, same ingredients, same scoring system).

For example, given the ingredients above, if you had instead selected `40` teaspoons of butterscotch and `60` teaspoons of cinnamon (which still adds to `100`), the total calorie count would be `40*8 + 60*3 = 500`. The total score would go down, though: only `57600000`, the best you can do in such trying circumstances.

Given the ingredients in your kitchen and their properties, what is the *total score* of the highest-scoring cookie you can make with a calorie total of `500`?

```{python}

score = 0
z = 'calories'

ings = list(ing.keys())
prop = list(ing['Sprinkles'].keys())[:-1]

for c in counter:
    s = [0,0,0,0]
    for e,i in enumerate(ings):
        for f,p in enumerate(prop):
            s[f] += ing[i][p] * c[e]
    # check scores and calories    
    sc = max(0,s[0]) * max(0,s[1]) * max(0,s[2]) * max(0,s[3])
    cal = sum([ing[i][z] * c[e] for e,i in enumerate(ings)])
    if sc > score and cal == 500:
        score = sc

print(score)

```
