---
title: "Advent of Code 2015 Day 21"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 21: RPG Simulator 20XX \-\--

Little Henry Case got a new video game for Christmas. It's an [RPG](https://en.wikipedia.org/wiki/Role-playing_video_game), and he's stuck on a boss. He needs to know what equipment to buy at the shop. He hands you the [controller](https://en.wikipedia.org/wiki/Game_controller).

In this game, the player (you) and the enemy (the boss) take turns attacking. The player always goes first. Each attack reduces the opponent's hit points by at least `1`. The first character at or below `0` hit points loses.

Damage dealt by an attacker each turn is equal to the attacker's damage score minus the defender's armor score. An attacker always does at least `1` damage. So, if the attacker has a damage score of `8`, and the defender has an armor score of `3`, the defender loses `5` hit points. If the defender had an armor score of `300`, the defender would still lose `1` hit point.

Your damage score and armor score both start at zero. They can be increased by buying items in exchange for gold. You start with no items and have as much gold as you need. Your total damage or armor is equal to the sum of those stats from all of your items. You have *100 hit points*.

Here is what the item shop is selling:

    Weapons:    Cost  Damage  Armor
    Dagger        8     4       0
    Shortsword   10     5       0
    Warhammer    25     6       0
    Longsword    40     7       0
    Greataxe     74     8       0

    Armor:      Cost  Damage  Armor
    Leather      13     0       1
    Chainmail    31     0       2
    Splintmail   53     0       3
    Bandedmail   75     0       4
    Platemail   102     0       5

    Rings:      Cost  Damage  Armor
    Damage +1    25     1       0
    Damage +2    50     2       0
    Damage +3   100     3       0
    Defense +1   20     0       1
    Defense +2   40     0       2
    Defense +3   80     0       3

You must buy exactly one weapon; no dual-wielding. Armor is optional, but you can't use more than one. You can buy 0-2 rings (at most one for each hand). You must use any items you buy. The shop only has one of each item, so you can't buy, for example, two rings of Damage +3.

For example, suppose you have `8` hit points, `5` damage, and `5` armor, and that the boss has `12` hit points, `7` damage, and `2` armor:

-   The player deals `5-2 = 3` damage; the boss goes down to 9 hit points.

-   The boss deals `7-5 = 2` damage; the player goes down to 6 hit points.

-   The player deals `5-2 = 3` damage; the boss goes down to 6 hit points.

-   The boss deals `7-5 = 2` damage; the player goes down to 4 hit points.

-   The player deals `5-2 = 3` damage; the boss goes down to 3 hit points.

-   The boss deals `7-5 = 2` damage; the player goes down to 2 hit points.

-   The player deals `5-2 = 3` damage; the boss goes down to 0 hit points.

In this scenario, the player wins! (Barely.)

You have *100 hit points*. The boss's actual stats are in your puzzle input. What is *the least amount of gold you can spend* and still win the fight?

```{python}

# Boss
# Hit Points: 109
# Damage: 8
# Armor: 2

b_hp = 109
b_d = 8
b_a = 2

# me
m_hp = 100

```

How long can we survive with different damage and armor variables?

```{python}

def battle(dam, def_):
    # how many turns I can survive for
    m_turns = m_hp / max(b_d - def_, 1)
    # how many turns the boss can survive for
    b_turns = b_hp / max(dam - b_a, 1)
    # if I can survive longer than the boss, then I win
    return m_turns > b_turns

```

Lists of damage and armor possibilities

```{python}
# Weapons:    Cost  Damage  Armor
# Dagger        8     4       0
# Shortsword   10     5       0
# Warhammer    25     6       0
# Longsword    40     7       0
# Greataxe     74     8       0
# 
# Armor:      Cost  Damage  Armor
# Leather      13     0       1
# Chainmail    31     0       2
# Splintmail   53     0       3
# Bandedmail   75     0       4
# Platemail   102     0       5
# 
# Rings:      Cost  Damage  Armor
# Damage +1    25     1       0
# Damage +2    50     2       0
# Damage +3   100     3       0
# Defense +1   20     0       1
# Defense +2   40     0       2
# Defense +3   80     0       3

weapons_cost = [8, 10, 25, 40, 74]
weapons_damage = [4, 5, 6, 7, 8]
rings_cost_d = [0, 25, 50, 100]
rings_damage = [0, 1, 2, 3]

armor_cost = [0, 13, 31, 53, 75, 102]
armor_defense = [0, 1, 2, 3, 4, 5]
rings_cost_a = [0, 20, 40, 80]
rings_defense = [0, 1, 2, 3]

```

It looks like I want to use product to create a dataframe

```{python}

import pandas as pd
import itertools

result = pd.DataFrame(list(itertools.product(weapons_damage, 
                                             rings_damage, 
                                             armor_defense, 
                                             rings_defense))
                     ).rename(columns={0:'w_dam', 1:'r_dam', 2:'a_def', 3:'r_def'})

result['dam'] = result['w_dam'] + result['r_dam']
result['def'] = result['a_def'] + result['r_def']

wpc = pd.DataFrame([weapons_cost, weapons_damage], index=['wpc', 'w_dam']).T
rcd = pd.DataFrame([rings_cost_d, rings_damage], index=['rcd', 'r_dam']).T
arc = pd.DataFrame([armor_cost, armor_defense], index=['arc', 'a_def']).T
rca = pd.DataFrame([rings_cost_a, rings_defense], index=['rca', 'r_def']).T

result = pd.merge(result, wpc, on='w_dam')
result = pd.merge(result, rcd, on='r_dam')
result = pd.merge(result, arc, on='a_def')
result = pd.merge(result, rca, on='r_def')

result['cost'] = result['wpc'] + result['rcd'] + result['arc'] + result['rca']

result['win'] = result.apply(lambda row: battle(row['dam'], row['def']), axis=1)

result[result['win']==True].nsmallest(1, 'cost')

```

## \-\-- Part Two \-\--

Turns out the shopkeeper is working with the boss, and can persuade you to buy whatever items he wants. The other rules still apply, and he still only has one of each item.

What is the *most* amount of gold you can spend and still *lose* the fight?

```{python}

result[result['win']==False].nlargest(1, 'cost')

```
