---
title: "Advent of Code Day 6"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 6: Probably a Fire Hazard \-\--

Because your neighbors keep defeating you in the holiday house decorating contest year after year, you've decided to deploy one million lights in a 1000x1000 grid.

Furthermore, because you've been especially nice this year, Santa has mailed you instructions on how to display the ideal lighting configuration.

Lights in your grid are numbered from 0 to 999 in each direction; the lights at each corner are at `0,0`, `0,999`, `999,999`, and `999,0`. The instructions include whether to `turn on`, `turn off`, or `toggle` various inclusive ranges given as coordinate pairs. Each coordinate pair represents opposite corners of a rectangle, inclusive; a coordinate pair like `0,0 through 2,2` therefore refers to 9 lights in a 3x3 square. The lights all start turned off.

To defeat your neighbors this year, all you have to do is set up your lights by doing the instructions Santa sent you in order.

For example:

-   `turn on 0,0 through 999,999` would turn on (or leave on) every light.

-   `toggle 0,0 through 999,0` would toggle the first line of 1000 lights, turning off the ones that were on, and turning on the ones that were off.

-   `turn off 499,499 through 500,500` would turn off (or leave off) the middle four lights.

After following the instructions, *how many lights are lit*?

```{python}
import re
import numpy as np

with open('data-2015-6.txt', 'r') as f:
    instructions = f.read().splitlines()

```

Prepare the instructions

```{python}
ins = [[0] * 5 for _ in range(len(instructions))]
reg1 = r'^(.+?)\d'
reg2 = r' (\d.*?),'
reg3 = r',(\d{1,3})'

for i in range(len(instructions)):
    ins[i][0] = re.findall(reg1, instructions[i])[0].strip() # instruction
    ins[i][1] = int(re.findall(reg2, instructions[i])[0].strip()) # x1
    ins[i][2] = int(re.findall(reg3, instructions[i])[0].strip()) # y1
    ins[i][3] = int(re.findall(reg2, instructions[i])[1].strip()) # x2
    ins[i][4] = int(re.findall(reg3, instructions[i])[1].strip()) # y2

```

Create the grid of lights

```{python}
lights = np.full((1000, 1000), False)

```

Apply the instructions

```{python}
for i in ins:
    if i[0] == 'turn on':
        lights[i[1]:i[3]+1, i[2]:i[4]+1] = True
    elif i[0] == 'turn off':
        lights[i[1]:i[3]+1, i[2]:i[4]+1] = False
    else:       # toggle
        for x in range(i[1], i[3] + 1):
            for y in range(i[2], i[4] + 1):
                lights[x, y] = not lights[x, y]


```

How many lights are on?

```{python}
lights.sum()

```

## \-\-- Part Two \-\--

You just finish implementing your winning light pattern when you realize you mistranslated Santa's message from Ancient Nordic Elvish.

The light grid you bought actually has individual brightness controls; each light can have a brightness of zero or more. The lights all start at zero.

The phrase `turn on` actually means that you should increase the brightness of those lights by `1`.

The phrase `turn off` actually means that you should decrease the brightness of those lights by `1`, to a minimum of zero.

The phrase `toggle` actually means that you should increase the brightness of those lights by `2`.

What is the *total brightness* of all lights combined after following Santa's instructions?

For example:

-   `turn on 0,0 through 0,0` would increase the total brightness by `1`.

-   `toggle 0,0 through 999,999` would increase the total brightness by `2000000`.

This time we are tracking brightness so start with zeros

```{python}
lights = np.full((1000, 1000), 0)
```

Modify our instructions

```{python}
for i in ins:
    if i[0] == 'turn on':
        lights[i[1]:i[3]+1, i[2]:i[4]+1] = lights[i[1]:i[3]+1, i[2]:i[4]+1] + 1
    elif i[0] == 'turn off':
        lights[i[1]:i[3]+1, i[2]:i[4]+1] = lights[i[1]:i[3]+1, i[2]:i[4]+1] - 1
        np.place(lights, lights<0, 0)
    else:       # toggle
        lights[i[1]:i[3]+1, i[2]:i[4]+1] = lights[i[1]:i[3]+1, i[2]:i[4]+1] + 2


```

Sum of the brightness

```{python}
lights.sum()

```
