---
title: "Advent of Code 2022 Day 22"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 22: Monkey Map \-\--

The monkeys take you on a surprisingly easy trail through the jungle. They're even going in roughly the right direction according to your handheld device's Grove Positioning System.

As you walk, the monkeys explain that the grove is protected by a *force field*. To pass through the force field, you have to enter a password; doing so involves tracing a specific *path* on a strangely-shaped board.

At least, you're pretty sure that's what you have to do; the elephants aren't exactly fluent in monkey.

The monkeys give you notes that they took when they last saw the password entered (your puzzle input).

For example:

            ...#
            .#..
            #...
            ....
    ...#.......#
    ........#...
    ..#....#....
    ..........#.
            ...#....
            .....#..
            .#......
            ......#.

    10R5L5R10L4R5L5

The first half of the monkeys' notes is a *map of the board*. It is comprised of a set of *open tiles* (on which you can move, drawn `.`) and *solid walls* (tiles which you cannot enter, drawn `#`).

The second half is a description of *the path you must follow*. It consists of alternating numbers and letters:

-   A *number* indicates the *number of tiles to move* in the direction you are facing. If you run into a wall, you stop moving forward and continue with the next instruction.

-   A *letter* indicates whether to turn 90 degrees *clockwise* (`R`) or *counterclockwise* (`L`). Turning happens in-place; it does not change your current tile.

So, a path like `10R5` means "go forward 10 tiles, then turn clockwise 90 degrees, then go forward 5 tiles".

You begin the path in the leftmost open tile of the top row of tiles. Initially, you are facing *to the right* (from the perspective of how the map is drawn).

If a movement instruction would take you off of the map, you *wrap around* to the other side of the board. In other words, if your next tile is off of the board, you should instead look in the direction opposite of your current facing as far as you can until you find the opposite edge of the board, then reappear there.

For example, if you are at `A` and facing to the right, the tile in front of you is marked `B`; if you are at `C` and facing down, the tile in front of you is marked `D`:

            ...#
            .#..
            #...
            ....
    ...#.D.....#
    ........#...
    B.#....#...A
    .....C....#.
            ...#....
            .....#..
            .#......
            ......#.

It is possible for the next tile (after wrapping around) to be a *wall*; this still counts as there being a wall in front of you, and so movement stops before you actually wrap to the other side of the board.

By drawing the *last facing you had* with an arrow on each tile you visit, the full path taken by the above example looks like this:

            >>v#    
            .#v.    
            #.v.    
            ..v.    
    ...#...v..v#    
    >>>v...>#.>>    
    ..#v...#....    
    ...>>>>v..#.    
            ...#....
            .....#..
            .#......
            ......#.

To finish providing the password to this strange input device, you need to determine numbers for your final *row*, *column*, and *facing* as your final position appears from the perspective of the original map. Rows start from `1` at the top and count downward; columns start from `1` at the left and count rightward. (In the above example, row 1, column 1 refers to the empty space with no tile on it in the top-left corner.) Facing is `0` for right (`>`), `1` for down (`v`), `2` for left (`<`), and `3` for up (`^`). The *final password* is the sum of 1000 times the row, 4 times the column, and the facing.

In the above example, the final row is `6`, the final column is `8`, and the final facing is `0`. So, the final password is 1000 \* 6 + 4 \* 8 + 0: *`6032`*.

Follow the path given in the monkeys' notes. *What is the final password?*

```{python}

import re
import numpy as np

with open('data-2022-22.txt', 'r') as f:
    inp = f.read().splitlines()

```

Data ~~preparation~~ inspection first

```{python}

inp[0]
inp[1]
inp[-1]
inp[-2]
inp[-3]

list(inp[0])
```

Let's prepare the instructions

```{python}
instr = re.split('(\d+)', inp[-1])

instr = instr[1:-1]

for i in range(0, len(instr), 2):
    instr[i] = int(instr[i])

instr[:20]
```

Let's prepare the grid

```{python}

inp[0]
inp[1]

# for i in inp[:-2]:
#     len(i)

gg = [i.ljust(150) for i in inp[:-2]]

# for i in gg:
#     len(i)

# split doesn't work for spliiting with spaces
gg[0].split()

# re.findall() works
re.findall('.', gg[0])

grid = np.array([re.findall('.', i) for i in gg])

grid

''.join(grid[0,:])
''.join(grid[75,:])
''.join(grid[125,:])
''.join(grid[175,:])

# this is our start space
grid[0,49]
grid[0,50]

np.shape(grid)
```

I think this will work fine. If a position is a space, keep going through until we find a `.` or a `#` . We also need to deal with wrapping around to the far side of the board.

I usually think about `x,y` coordinates but for index of array then we need to use something different. `+x` is second element, `-y` is increasing the first element. Let's use `i,j` instead.

```{python}

i = 0
j = 50

m = '>'

L = {'>': '^', 
     '^': '<', 
     '<': 'v', 
     'v': '>'}
R = {'>': 'v', 
     'v': '<', 
     '<': '^', 
     '^': '>'}

facing = {'>': 0, 
          'v': 1, 
          '<': 2, 
          '^': 3}


def rotator(m, z): 
    if z == 'L': 
        m = L[m]
    else: 
        # z == 'R'
        m = R[m]
    return m


def normal_movement(m):
    if m == '>':
        _i = 0
        _j = +1
    elif m == '<':
        _i = 0
        _j = -1
    elif m == 'v': 
        _i = +1
        _j = 0
    elif m == '^': 
        _i = -1
        _j = 0
    return _i, _j


def limits(m, i, j, _i, _j):
    b = False
    w = False
    if m == '>':
        if j == 149:
            j = -1
            i, j = skip_spaces2(m, i, j, _i, _j)
    elif m == '<':
        if j == 0:
            j = 150
            i, j = skip_spaces2(m, i, j, _i, _j)
    elif m == 'v': 
        if i == 199:
            i = -1
            i, j = skip_spaces2(m, i, j, _i, _j)
    elif m == '^': 
        if i == 0: 
            i = 200
            i, j = skip_spaces2(m, i, j, _i, _j)
    return i, j, b


def skip_spaces(m, i, j, _i, _j):
    if m == '>':
        j = -1
        i, j = skip_spaces2(m, i, j, _i, _j)
    elif m == '<':
        j = 150
        i, j = skip_spaces2(m, i, j, _i, _j)
    elif m == 'v': 
        i = -1
        i, j = skip_spaces2(m, i, j, _i, _j)
    elif m == '^': 
        i = 200
        i, j = skip_spaces2(m, i, j, _i, _j)
    return i, j


def skip_spaces2(m, i, j, _i, _j):
    a = i
    b = j
    while True:
        if grid[a+_i,b+_j] == ' ':
            a += _i
            b += _j
        elif grid[a+_i,b+_j] == '#':
            return i, j
        elif grid[a+_i,b+_j] == '.': 
            return a, b


def mover(m, i, j, k):
    # normal movement directions
    _i, _j = normal_movement(m)
    # take as many steps as we can
    for s in range(k):
        # check if we've reached the limit of the array / board
        i, j, b = limits(m, i, j, _i, _j)
        if b:
            # we would wrap around into a wall
            break
        # if we are moving normally then check for a wall
        elif grid[i+_i, j+_j] == '#':
            break
        # if we run into a space, then iterate through that
        elif grid[i+_i, j+_j] == ' ':
            i, j = skip_spaces(m, i, j, _i, _j)
        # we're safe to move a square and iterate the direction
        i += _i
        j += _j
        print(i, j)
    return i, j


# if name == main
for k in instr:
    if isinstance(k, int):
        print(k)
        # movement
        i, j = mover(m, i, j, k)
    else: 
        # change direction
        m = rotator(m, k)
        print(m)


1000 * (i+1) + 4 * (j+1) + facing[m]
```
