---
title: "Advent of Code 2022 Day 18"
author: "Nathan Moore"
format: html
editor: visual
---

## \-\-- Day 18: Boiling Boulders \-\--

You and the elephants finally reach fresh air. You've emerged near the base of a large volcano that seems to be actively erupting! Fortunately, the lava seems to be flowing away from you and toward the ocean.

Bits of lava are still being ejected toward you, so you're sheltering in the cavern exit a little longer. Outside the cave, you can see the lava landing in a pond and hear it loudly hissing as it solidifies.

Depending on the specific compounds in the lava and speed at which it cools, it might be forming [obsidian](https://en.wikipedia.org/wiki/Obsidian)! The cooling rate should be based on the surface area of the lava droplets, so you take a quick scan of a droplet as it flies past you (your puzzle input).

Because of how quickly the lava is moving, the scan isn't very good; its resolution is quite low and, as a result, it approximates the shape of the lava droplet with *1x1x1 cubes on a 3D grid*, each given as its `x,y,z` position.

To approximate the surface area, count the number of sides of each cube that are not immediately connected to another cube. So, if your scan were only two adjacent cubes like `1,1,1` and `2,1,1`, each cube would have a single side covered and five sides exposed, a total surface area of *`10`* sides.

Here's a larger example:

    2,2,2
    1,2,2
    3,2,2
    2,1,2
    2,3,2
    2,2,1
    2,2,3
    2,2,4
    2,2,6
    1,2,5
    3,2,5
    2,1,5
    2,3,5

In the above example, after counting up all the sides that aren't connected to another cube, the total surface area is *`64`*.

*What is the surface area of your scanned lava droplet?*

```{python}

import numpy as np

with open('data-2022-18.txt', 'r') as f:
    inp = f.read().splitlines()

```

I prefer these ones that have a distinct answer (probably).

```{python}

cubes = [list(map(int, x.split(','))) for x in inp]

cubes[0]

min(cubes)
max(cubes)

cc = np.zeros((22,22,22))
dd = np.zeros((22,22,22))

for w in cubes: 
    x,y,z = w
    cc[x,y,z] = 1


def assess_cube(x,y,z):
    s = 0
    if x == 0: 
        s += 1
    else: 
        if cc[x-1,y,z] == 0:
            s += 1
    if x == 21: 
        s += 1        
    else: 
        if cc[x+1,y,z] == 0:
            s += 1
    if y == 0:
        s += 1
    else: 
        if cc[x,y-1,z] == 0:
            s += 1
    if y == 21: 
        s += 1
    else:
        if cc[x,y+1,z] == 0:
            s += 1
    if z == 0:
        s += 1
    else: 
        if cc[x,y,z-1] == 0:
            s += 1
    if z == 21:
        s += 1
    else:
        if cc[x,y,z+1] == 0:
            s += 1
    return s

    
for x in range(22): 
    for y in range(22):
        for z in range(22): 
            if cc[x,y,z] == 1:
                dd[x,y,z] = assess_cube(x,y,z)

np.sum(dd)

```

## \-\-- Part Two \-\--

Something seems off about your calculation. The cooling rate depends on exterior surface area, but your calculation also included the surface area of air pockets trapped in the lava droplet.

Instead, consider only cube sides that could be reached by the water and steam as the lava droplet tumbles into the pond. The steam will expand to reach as much as possible, completely displacing any air on the outside of the lava droplet but never expanding diagonally.

In the larger example above, exactly one cube of air is trapped within the lava droplet (at `2,2,5`), so the exterior surface area of the lava droplet is *`58`*.

*What is the exterior surface area of your scanned lava droplet?*

Alter the counter array dd to subtract any inner air pockets

```{python}

def pockets(x,y,z):
    if (
      cc[x-1,y,z] == 1 and 
      cc[x+1,y,z] == 1 and 
      cc[x,y-1,z] == 1 and 
      cc[x,y+1,z] == 1 and 
      cc[x,y,z-1] == 1 and 
      cc[x,y,z+1] == 1):
        return -6
    else:
        return 0


for x in range(1,21): 
    for y in range(1,21):
        for z in range(1,21): 
            if cc[x,y,z] == 0:
                dd[x,y,z] = pockets(x,y,z)


np.sum(dd)

```
