---
title: "2021 Day 15"
author: "Nathan Moore"
format: html
editor: visual
---

## --- Day 15: Chiton ---

The cave roof is getting lower and you can only move in two dimensions.

*What is the lowest total risk of any path from the top left to the bottom right?*

```{r}

library(tidyverse)
library(igraph)

my_file <- here::here("2021", "data-2021-15.txt")
x = read_fwf(my_file, fwf_widths(rep_len(1,100), col_names = 1:100))
x = as.matrix(x)
```

Create a matrix and use some kind of graph movement.

```{r}

define_edges = function(i, j) {
        if (i == 1 & j == 1) {
            e = list(c(1,0), c(0,1))
        } else if (i == 1 & j == 100) {
            e = list(c(1,0), c(0,-1)) 
        } else if (i == 100 & j == 1) {
            e = list(c(-1,0), c(0,1))
        } else if (i == 100 & j == 100) {
            e = list(c(-1,0), c(0,-1))
        } else if (i == 1) {
            e = list(c(1,0), c(0,1), c(0,-1))
        } else if (j == 1) {
            e = list(c(-1,0), c(1,0), c(0,1))
        } else if (i == 100) { 
            e = list(c(-1,0), c(0,1), c(0,-1))
        } else if (j == 100) { 
            e = list(c(-1,0), c(1,0), c(0,-1))
        } else {
            e = list(c(1,0), c(0,1), c(-1,0), c(0,-1))
        }
        
    return(e)
}
```

```{r}

g = make_empty_graph(n=10000, directed=TRUE)

for (i in 1:100) { 
    for (j in 1:100) { 
        # define edges that we can move on
        e = define_edges(i,j)
        for (d in e) {
            a = i + d[1]
            b = j + d[2]
            outo = (a-1)*100 + b # from this node
            into = (i-1)*100 + j # into this node
            # cat(outo, into, "\n")
            # print(into)
            g = add_edges(g, c(outo,into), weight=x[i,j])
        }
    }
}


```

Solve?

```{r}

distances(g, 1, 10000)

shortest_paths(g, 1, 10000)


```
